### PR TITLE
Add new checks

### PR DESCRIPTION
**Pull request by rverchere**
- Rename grid usage to h-a usage (based on OID informations)
- Add service check
- Add DNS View check
- Add SWAP check

### CODE REVIEW

**Comment by Napsty** [comment]
Hello @rverchere 
Thanks for the PR!
Sorry for this huge delay. Github never notified me on this PR :-/

As I don't have an Infoblox appliance anymore, I cannot test this PR. Can you show the output of the plugin with your modifications please? You can of course obfuscate sensitive data.

**Comment by rverchere** [comment]
Hi @Napsty , here are the output:

```
#./check_infoblox.sh -H 192.168.1.123 -C mycommunity -V 2c  -t swap -w 80 -c 90
SWAP OK - Usage at 0%|ibloxswap=0%;80;90;;
# ./check_infoblox.sh -H 192.168.1.123 -C mycommunity -V 2c -t dnsview -a "Private View"
DNS View Private View exists
# echo $?
0
# ./check_infoblox.sh -H 192.168.1.123 -C mycommunity -V 2c -t dnsview -a "Private View" -n
DNS View Private View exists
# echo $?
2
# ./check_infoblox.sh -H 192.168.1.123 -C mycommunity -V 2c -t service -a dns
"DNS Service is working"
```

Thanks!

**Comment by Napsty** [comment]
OK just one minor comment, otherwise lgtm. 

The service check requires an additional argument. It would be helpful to show this in the "help" output which input is expected. For example `dns, ntp, dhcp, ...`, Could you please add the this information somewhere in the help output?

**Comment by rverchere** [comment]
> The service check requires an additional argument. It would be helpful to show this in the "help" output which input is expected. For example `dns, ntp, dhcp, ...`, Could you please add the this information somewhere in the help output?

Done, also added/corrected ouput, adding OK, WARNING & co in stdout.

**Review by Napsty — APPROVED** [review]

**Pull request merged**
